### ISSUE TITLE
Support indexing ambiguity for all cases

### ISSUE THREAD

**Issue by biochem-fan** [helenginn/cppxfel#24]
Currently, the hard-coded table is incomplete. For example, I4 to I422 ambiguity is missing.

Also, we would like to have an option to specify an operator to support metric symmetry. An example is myoglobin in P21 (3VAU). See explanation in README of find_ambi program http://www.desy.de/~twhite/crystfel/programs.html.

**Comment by helenginn** [comment]
CUSTOM_AMBIGUITY added.
